-- Migration: add admission-form fields to existing students table
-- Run this once on your existing database.

ALTER TABLE students
  ADD COLUMN IF NOT EXISTS Father_Name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS Mother_Name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS Gender VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS Date_of_Birth DATE NULL,
  ADD COLUMN IF NOT EXISTS Category VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS Aadhaar VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS Father_Occupation VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS Mother_Occupation VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS Present_Address VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS Permanent_Address VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS District VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS State VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS Country VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS Section VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS Admission_Year VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS Scholarship_Eligible VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS Guardian_Mobile VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS Guardian_Email VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS SSC_School VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS SSC_Board VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS SSC_Year VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS SSC_Marks VARCHAR(30) NULL,
  ADD COLUMN IF NOT EXISTS Inter_College VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS Inter_Board VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS Inter_Year VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS Inter_Marks VARCHAR(30) NULL,
  ADD COLUMN IF NOT EXISTS UG_College VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS UG_Board VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS UG_Year VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS UG_Marks VARCHAR(30) NULL,
  ADD COLUMN IF NOT EXISTS PG_College VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS PG_Board VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS PG_Year VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS PG_Marks VARCHAR(30) NULL;

-- Optional: backfill sensible defaults for old rows where data is missing.
UPDATE students
SET
  Country = COALESCE(NULLIF(Country, ''), 'India'),
  Admission_Year = COALESCE(NULLIF(Admission_Year, ''), 'N/A'),
  Scholarship_Eligible = COALESCE(NULLIF(Scholarship_Eligible, ''), 'No'),
  Section = COALESCE(NULLIF(Section, ''), 'N/A');
