CREATE TABLE IF NOT EXISTS students (
  Student_ID VARCHAR(20) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Father_Name VARCHAR(255),
  Mother_Name VARCHAR(255),
  Gender VARCHAR(20),
  Date_of_Birth DATE,
  Category VARCHAR(50),
  Aadhaar VARCHAR(20),
  Father_Occupation VARCHAR(100),
  Mother_Occupation VARCHAR(100),
  Present_Address VARCHAR(500),
  Permanent_Address VARCHAR(500),
  District VARCHAR(100),
  State VARCHAR(100),
  Country VARCHAR(100),
  Section VARCHAR(50),
  Admission_Year VARCHAR(20),
  Scholarship_Eligible VARCHAR(20),
  Guardian_Mobile VARCHAR(20),
  Guardian_Email VARCHAR(255),
  SSC_School VARCHAR(255),
  SSC_Board VARCHAR(100),
  SSC_Year VARCHAR(20),
  SSC_Marks VARCHAR(30),
  Inter_College VARCHAR(255),
  Inter_Board VARCHAR(100),
  Inter_Year VARCHAR(20),
  Inter_Marks VARCHAR(30),
  UG_College VARCHAR(255),
  UG_Board VARCHAR(100),
  UG_Year VARCHAR(20),
  UG_Marks VARCHAR(30),
  PG_College VARCHAR(255),
  PG_Board VARCHAR(100),
  PG_Year VARCHAR(20),
  PG_Marks VARCHAR(30),
  Email VARCHAR(255) UNIQUE NOT NULL,
  Branch VARCHAR(100),
  Year INT,
  CGPA DECIMAL(3,2),
  Attendance_Percentage INT,
  Placement_Status VARCHAR(50),
  Company VARCHAR(100),
  Phone VARCHAR(20)
);

INSERT INTO students (
  Student_ID, Name, Father_Name, Mother_Name, Gender, Date_of_Birth, Category, Aadhaar,
  Father_Occupation, Mother_Occupation, Present_Address, Permanent_Address, District, State, Country,
  Section, Admission_Year, Scholarship_Eligible, Guardian_Mobile, Guardian_Email,
  SSC_School, SSC_Board, SSC_Year, SSC_Marks,
  Inter_College, Inter_Board, Inter_Year, Inter_Marks,
  UG_College, UG_Board, UG_Year, UG_Marks,
  PG_College, PG_Board, PG_Year, PG_Marks,
  Email, Branch, Year, CGPA, Attendance_Percentage, Placement_Status, Company, Phone
) VALUES
('STU001', 'Madhav B', 'Balaiah', 'Lakshmi', 'Male', '2006-01-15', 'BC-B', 'XXXX-XXXX-1927',
 'Farmer', 'Homemaker', 'Kothapeta, Hyderabad', 'Kothapeta, Hyderabad', 'Hyderabad', 'Telangana', 'India',
 'CSE-A', '2023-2024', 'No', '9000000001', 'guardian1@example.com',
 'ZPHS School', 'State Board', '2021', '9.7',
 'Sri Chaitanya Jr College', 'BIE Telangana', '2023', '95%',
 'MGIT', 'JNTUH', 'Pursuing', '8.5',
 NULL, NULL, NULL, NULL,
 'bmadhav349@gmail.com', 'Computer Science', 4, 8.5, 95, 'Placed', 'Google', '9876543210'),
('STU002', 'Asha Kumar', 'Ravi Kumar', 'Sujatha', 'Female', '2005-09-20', 'OC', 'XXXX-XXXX-4831',
 'Engineer', 'Teacher', 'Miyapur, Hyderabad', 'Miyapur, Hyderabad', 'Hyderabad', 'Telangana', 'India',
 'CSE-A', '2023-2024', 'No', '9000000002', 'guardian2@example.com',
 'St. Mary School', 'State Board', '2021', '9.8',
 'Narayana Jr College', 'BIE Telangana', '2023', '97%',
 'MGIT', 'JNTUH', 'Pursuing', '8.8',
 NULL, NULL, NULL, NULL,
 'asha.kumar@college.edu', 'Computer Science', 4, 8.8, 98, 'Placed', 'Microsoft', '9876543211'),
('STU003', 'Raj Patel', 'Mahesh Patel', 'Anita Patel', 'Male', '2005-06-12', 'BC-A', 'XXXX-XXXX-5520',
 'Shop Owner', 'Homemaker', 'Uppal, Hyderabad', 'Uppal, Hyderabad', 'Hyderabad', 'Telangana', 'India',
 'ECE-B', '2023-2024', 'Yes', '9000000003', 'guardian3@example.com',
 'Govt High School', 'State Board', '2021', '9.1',
 'SR Junior College', 'BIE Telangana', '2023', '90%',
 'MGIT', 'JNTUH', 'Pursuing', '7.9',
 NULL, NULL, NULL, NULL,
 'raj.patel@college.edu', 'Electronics', 3, 7.9, 88, 'Not Placed', NULL, '9876543212');

-- Add missing student for dashboard
INSERT INTO students (
  Student_ID, Name, Father_Name, Mother_Name, Gender, Date_of_Birth, Category, Aadhaar,
  Father_Occupation, Mother_Occupation, Present_Address, Permanent_Address, District, State, Country,
  Section, Admission_Year, Scholarship_Eligible,
  Email, Branch, Year, CGPA, Attendance_Percentage, Placement_Status, Company, Phone
) VALUES
('BT20260003', 'Test Student', 'Test Father', 'Test Mother', 'Male', '2005-01-01', 'General', 'XXXX-XXXX-0000',
 'Employee', 'Homemaker', 'Test Address, Hyderabad', 'Test Address, Hyderabad', 'Hyderabad', 'Telangana', 'India',
 'CSE-B', '2023-2024', 'No',
 'test.student@college.edu', 'Computer Science', 3, 7.5, 90, 'Not Placed', NULL, '9999999999');
